//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageStoreASP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ImageCodeEntities : DbContext
    {
        public ImageCodeEntities()
            : base("name=ImageCodeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerPayment> CustomerPayments { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<OrderMaterial> OrderMaterials { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderSize> OrderSizes { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
    }
}
